apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  POSTGRES_DB: "dGVjaC1jaGFsbGVuZ2UtZGI="
  POSTGRES_USER: "cG9zdGdyZXM="
  POSTGRES_PASSWORD: "cG9zdGdyZXM="
  USER_TOKEN_SECRET: "ZDA2MDFjOGViYzM2YzY4N2YwYmM0NDdhOGZhZmRmZWE0NWI0MGIyYzIwZjkzMDk3ZDAzM2M5YWMwODhmYWMxOA=="
